"""
Auto-generated NovaSight DAG
============================

DAG ID: novasight-demo_extract_users_pipeline
Version: 5
Generated: 2026-02-11T11:56:06.789376
Owner: novasight

WARNING: This file is auto-generated by NovaSight.
Do not edit manually - changes will be overwritten.

Spark submission: Uses native SparkSubmitOperator (preferred) or docker exec fallback.
"""
from __future__ import annotations

import os
from datetime import datetime, timedelta
import pendulum
from airflow.models.dag import DAG
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
from airflow.providers.smtp.operators.smtp import EmailOperator
from airflow.providers.http.sensors.http import HttpSensor
from airflow.sensors.time_sensor import TimeSensor
from airflow.utils.trigger_rule import TriggerRule

# ============================================
# Spark Configuration
# ============================================
SPARK_HOME = os.environ.get('SPARK_HOME', '/opt/spark')
SPARK_MASTER = os.environ.get('SPARK_MASTER', 'spark://spark-master:7077')
SPARK_MASTER_CONTAINER = os.environ.get('SPARK_MASTER_CONTAINER', 'novasight-spark-master')

# Check if native Spark is available (preferred)
SPARK_NATIVE_AVAILABLE = os.path.exists(f'{SPARK_HOME}/bin/spark-submit')

# JDBC JARs for database connectivity
JDBC_JARS = ','.join([
    f'{SPARK_HOME}/jars/custom/postgresql-42.7.4.jar',
    f'{SPARK_HOME}/jars/custom/clickhouse-jdbc-0.6.3.jar',
])


# Default arguments for all tasks
default_args = {
    'owner': 'novasight',
    'depends_on_past': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    'email_on_failure': False,
    'email_on_success': False,
}

# DAG Definition
with DAG(
    dag_id='novasight-demo_extract_users_pipeline',
    description='Data pipeline for extract_users - extracting from users to stg_users',
    default_args=default_args,
    schedule=None,
    start_date=pendulum.datetime(2024, 1, 1, tz='UTC'),
    catchup=False,
    max_active_runs=1,
    tags=["novasight-demo", "novasight-demo", "novasight-demo", "pyspark", "etl"],
) as dag:
    
    # Start task
    start = EmptyOperator(task_id='start')
    
    # End task
    end = EmptyOperator(task_id='end')
    
    # Task definitions
    tasks = {}
    
    # Task: spark_submit_1770810936388
    # Spark Submit Task: spark_submit_1770810936388
    if SPARK_NATIVE_AVAILABLE:
        # Use native SparkSubmitOperator (preferred)
        tasks['spark_submit_1770810936388'] = SparkSubmitOperator(
            task_id='spark_submit_1770810936388',
            application='/opt/spark/jobs/extract_users.py',
            conn_id='spark_default',
            jars=JDBC_JARS,
            executor_memory='2g',
            executor_cores=2,
            driver_memory='1g',
            conf={
                'spark.executor.memory': '2g',
                'spark.executor.cores': '2',
            },
            execution_timeout=timedelta(minutes=60),
            retries=1,
            retry_delay=timedelta(minutes=5),
            trigger_rule=TriggerRule.ALL_SUCCESS,
        )
    else:
        # Fallback to docker exec
        spark_submit_1770810936388_cmd = f"""
docker exec {SPARK_MASTER_CONTAINER} /opt/spark/bin/spark-submit \\
    --master spark://spark-master:7077 \\
    --deploy-mode client \\
    --driver-memory 1g \\
    --executor-memory 2g \\
    --executor-cores 2 \\
    --jars /opt/spark/jars/custom/postgresql-42.7.4.jar,/opt/spark/jars/custom/clickhouse-jdbc-0.6.3.jar \\
    /opt/spark/jobs/extract_users.py
"""
        tasks['spark_submit_1770810936388'] = BashOperator(
            task_id='spark_submit_1770810936388',
            bash_command=spark_submit_1770810936388_cmd,
            execution_timeout=timedelta(minutes=60),
            retries=1,
            retry_delay=timedelta(minutes=5),
            trigger_rule=TriggerRule.ALL_SUCCESS,
        )
    

# ============================================
# Task Dependencies
# ============================================
# Dependencies are set at the end after all tasks are defined
# to ensure proper resolution regardless of conditional task creation

# Connect start to all root tasks (tasks with no dependencies)
start >> [tasks['spark_submit_1770810936388']]

# Define explicit task dependencies

# Connect all leaf tasks (tasks that nothing depends on) to end
[tasks['spark_submit_1770810936388']] >> end
