/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        /* ---- Shadcn UI compatibility ---- */
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50:  'hsl(var(--color-primary-50))',
          100: 'hsl(var(--color-primary-100))',
          200: 'hsl(var(--color-primary-200))',
          300: 'hsl(var(--color-primary-300))',
          400: 'hsl(var(--color-primary-400))',
          500: 'hsl(var(--color-primary-500))',
          600: 'hsl(var(--color-primary-600))',
          700: 'hsl(var(--color-primary-700))',
          800: 'hsl(var(--color-primary-800))',
          900: 'hsl(var(--color-primary-900))',
          950: 'hsl(var(--color-primary-950))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50:  'hsl(var(--color-secondary-50))',
          100: 'hsl(var(--color-secondary-100))',
          200: 'hsl(var(--color-secondary-200))',
          300: 'hsl(var(--color-secondary-300))',
          400: 'hsl(var(--color-secondary-400))',
          500: 'hsl(var(--color-secondary-500))',
          600: 'hsl(var(--color-secondary-600))',
          700: 'hsl(var(--color-secondary-700))',
          800: 'hsl(var(--color-secondary-800))',
          900: 'hsl(var(--color-secondary-900))',
          950: 'hsl(var(--color-secondary-950))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          50:  'hsl(var(--color-accent-50))',
          100: 'hsl(var(--color-accent-100))',
          200: 'hsl(var(--color-accent-200))',
          300: 'hsl(var(--color-accent-300))',
          400: 'hsl(var(--color-accent-400))',
          500: 'hsl(var(--color-accent-500))',
          600: 'hsl(var(--color-accent-600))',
          700: 'hsl(var(--color-accent-700))',
          800: 'hsl(var(--color-accent-800))',
          900: 'hsl(var(--color-accent-900))',
          950: 'hsl(var(--color-accent-950))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        /* ---- NovaSight Semantic Colors ---- */
        success: {
          DEFAULT: 'hsl(var(--color-success))',
          50:  'hsl(var(--color-success-50))',
          100: 'hsl(var(--color-success-100))',
          200: 'hsl(var(--color-success-200))',
          300: 'hsl(var(--color-success-300))',
          400: 'hsl(var(--color-success-400))',
          500: 'hsl(var(--color-success-500))',
          600: 'hsl(var(--color-success-600))',
          700: 'hsl(var(--color-success-700))',
          800: 'hsl(var(--color-success-800))',
          900: 'hsl(var(--color-success-900))',
          950: 'hsl(var(--color-success-950))',
        },
        warning: {
          DEFAULT: 'hsl(var(--color-warning))',
          50:  'hsl(var(--color-warning-50))',
          100: 'hsl(var(--color-warning-100))',
          200: 'hsl(var(--color-warning-200))',
          300: 'hsl(var(--color-warning-300))',
          400: 'hsl(var(--color-warning-400))',
          500: 'hsl(var(--color-warning-500))',
          600: 'hsl(var(--color-warning-600))',
          700: 'hsl(var(--color-warning-700))',
          800: 'hsl(var(--color-warning-800))',
          900: 'hsl(var(--color-warning-900))',
          950: 'hsl(var(--color-warning-950))',
        },
        danger: {
          DEFAULT: 'hsl(var(--color-error))',
          50:  'hsl(var(--color-danger-50))',
          100: 'hsl(var(--color-danger-100))',
          200: 'hsl(var(--color-danger-200))',
          300: 'hsl(var(--color-danger-300))',
          400: 'hsl(var(--color-danger-400))',
          500: 'hsl(var(--color-danger-500))',
          600: 'hsl(var(--color-danger-600))',
          700: 'hsl(var(--color-danger-700))',
          800: 'hsl(var(--color-danger-800))',
          900: 'hsl(var(--color-danger-900))',
          950: 'hsl(var(--color-danger-950))',
        },
        info: {
          DEFAULT: 'hsl(var(--color-info))',
          50:  'hsl(var(--color-info-50))',
          100: 'hsl(var(--color-info-100))',
          200: 'hsl(var(--color-info-200))',
          300: 'hsl(var(--color-info-300))',
          400: 'hsl(var(--color-info-400))',
          500: 'hsl(var(--color-info-500))',
          600: 'hsl(var(--color-info-600))',
          700: 'hsl(var(--color-info-700))',
          800: 'hsl(var(--color-info-800))',
          900: 'hsl(var(--color-info-900))',
          950: 'hsl(var(--color-info-950))',
        },
        neutral: {
          50:  'hsl(var(--color-neutral-50))',
          100: 'hsl(var(--color-neutral-100))',
          200: 'hsl(var(--color-neutral-200))',
          300: 'hsl(var(--color-neutral-300))',
          400: 'hsl(var(--color-neutral-400))',
          500: 'hsl(var(--color-neutral-500))',
          600: 'hsl(var(--color-neutral-600))',
          700: 'hsl(var(--color-neutral-700))',
          800: 'hsl(var(--color-neutral-800))',
          900: 'hsl(var(--color-neutral-900))',
          950: 'hsl(var(--color-neutral-950))',
        },
        /* ---- Surface aliases ---- */
        'bg-primary': 'hsl(var(--color-bg-primary))',
        'bg-secondary': 'hsl(var(--color-bg-secondary))',
        'bg-tertiary': 'hsl(var(--color-bg-tertiary))',
        'bg-elevated': 'hsl(var(--color-bg-elevated))',
        /* ---- Legacy aliases (use semantic names in new code) ---- */
        'accent-indigo': 'hsl(var(--color-accent-indigo))',
        'accent-purple': 'hsl(var(--color-accent-purple))',
        'accent-violet': 'hsl(var(--color-accent-violet))',
        'neon-cyan': 'hsl(var(--color-neon-cyan))',
        'neon-pink': 'hsl(var(--color-neon-pink))',
        'neon-green': 'hsl(var(--color-neon-green))',
        error: 'hsl(var(--color-error))',
        /* ---- Chart colors ---- */
        chart: {
          1: 'hsl(var(--color-chart-1))',
          2: 'hsl(var(--color-chart-2))',
          3: 'hsl(var(--color-chart-3))',
          4: 'hsl(var(--color-chart-4))',
          5: 'hsl(var(--color-chart-5))',
          6: 'hsl(var(--color-chart-6))',
          7: 'hsl(var(--color-chart-7))',
          8: 'hsl(var(--color-chart-8))',
          9: 'hsl(var(--color-chart-9))',
          10: 'hsl(var(--color-chart-10))',
          axis: 'hsl(var(--color-chart-axis))',
          grid: 'hsl(var(--color-chart-grid))',
          tick: 'hsl(var(--color-chart-tick))',
          label: 'hsl(var(--color-chart-label))',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
      spacing: {
        'sidebar-collapsed': 'var(--sidebar-width-collapsed)',
        'sidebar-expanded': 'var(--sidebar-width-expanded)',
        'header': 'var(--header-height)',
        'mobile-nav': 'var(--mobile-nav-height)',
        'touch-target': 'var(--touch-target-min)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
      },
      boxShadow: {
        'glow-sm': 'var(--shadow-glow-sm)',
        'glow-md': 'var(--shadow-glow-md)',
        'glow-lg': 'var(--shadow-glow-lg)',
        'glow-neon': 'var(--shadow-glow-neon)',
        'glow-pink': 'var(--shadow-glow-pink)',
      },
      backdropBlur: {
        'glass': 'var(--glass-blur)',
        'glass-lg': 'var(--glass-blur-lg)',
      },
      transitionDuration: {
        'micro': 'var(--duration-micro)',
        'base': 'var(--duration-base)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'out-expo': 'var(--ease-out-expo)',
        'out-back': 'var(--ease-out-back)',
        'spring': 'var(--ease-spring)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'ai-pulse': {
          '0%, 100%': {
            boxShadow: '0 0 5px hsl(var(--color-accent-purple) / 0.4), 0 0 20px hsl(var(--color-accent-purple) / 0.2), 0 0 40px hsl(var(--color-accent-purple) / 0.1)',
          },
          '50%': {
            boxShadow: '0 0 10px hsl(var(--color-accent-purple) / 0.6), 0 0 30px hsl(var(--color-accent-purple) / 0.4), 0 0 60px hsl(var(--color-accent-purple) / 0.2)',
          },
        },
        'gradient-flow': {
          '0%': { backgroundPosition: '0% 0%' },
          '50%': { backgroundPosition: '100% 100%' },
          '100%': { backgroundPosition: '0% 0%' },
        },
        'shimmer': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0) translateX(0)' },
          '25%': { transform: 'translateY(-20px) translateX(10px)' },
          '50%': { transform: 'translateY(-10px) translateX(-10px)' },
          '75%': { transform: 'translateY(-25px) translateX(5px)' },
        },
        'typing-dot': {
          '0%, 20%': { opacity: '0.3', transform: 'translateY(0)' },
          '50%': { opacity: '1', transform: 'translateY(-4px)' },
          '80%, 100%': { opacity: '0.3', transform: 'translateY(0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-down': {
          from: { opacity: '0', transform: 'translateY(-20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'ai-pulse': 'ai-pulse 2s ease-in-out infinite',
        'gradient-flow': 'gradient-flow 8s ease infinite',
        'shimmer': 'shimmer 2s infinite',
        'float': 'float 6s ease-in-out infinite',
        'typing-dot': 'typing-dot 1.4s ease-in-out infinite',
        'fade-up': 'fade-up 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-down': 'fade-down 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'scale-in': 'scale-in 0.25s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'shake': 'shake 0.5s ease-in-out',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, hsl(var(--color-primary-500)), hsl(var(--color-accent-700)))',
        'gradient-accent': 'linear-gradient(135deg, hsl(var(--color-accent-700)), hsl(var(--color-accent-500)))',
        'gradient-brand': 'linear-gradient(135deg, hsl(var(--color-primary-600)), hsl(var(--color-accent-700)))',
        'gradient-teal': 'linear-gradient(135deg, hsl(var(--color-secondary-400)), hsl(var(--color-secondary-600)))',
        'gradient-neon': 'linear-gradient(135deg, hsl(var(--color-secondary-400)), hsl(var(--color-danger-400)))',
        'gradient-ai': 'linear-gradient(90deg, hsl(var(--color-accent-700)), hsl(var(--color-danger-400)), hsl(var(--color-accent-700)))',
        'gradient-glow': 'radial-gradient(ellipse at center, hsl(var(--color-primary-500) / 0.15) 0%, transparent 70%)',
        'grid-pattern': 'linear-gradient(to right, hsl(var(--color-border-subtle)) 1px, transparent 1px), linear-gradient(to bottom, hsl(var(--color-border-subtle)) 1px, transparent 1px)',
      },
      backgroundSize: {
        'grid': '40px 40px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
