{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: {{ include "novasight.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "novasight.backend.fullname" . }}
  labels:
    {{- include "novasight.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.backend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "novasight.backend.selectorLabels" . | nindent 6 }}
{{- end }}
