"""
PySpark SCD Type 2 Job: extract_staff_records
Generated by NovaSight Template Engine
Generated at: 2026-02-09T09:14:09.509675
Template Version: 1.0.0
App ID: 3ef7910b-8e7b-411b-9fd5-6f12c421a4d2
Tenant ID: 9b2ab68a-f819-41fa-bf51-916440c34cbd

SCD Type 2: Maintains full history with effective dates.
- New records get is_current=true, valid_from=now, valid_to=null
- Updated records: old record set to is_current=false, valid_to=now
- Insert new version with is_current=true

DO NOT MODIFY THIS FILE DIRECTLY.
All changes should be made through the NovaSight UI.
"""

from pyspark.sql import SparkSession, DataFrame, Window
from pyspark.sql.functions import (
    col, lit, current_timestamp, when, coalesce,
    row_number, max as spark_max, md5, concat_ws
)
from pyspark.sql.types import *
import logging
import os
import urllib.request
import urllib.parse
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("extract_staff_records")


class SCDType2Job:
    """
    SCD Type 2 job for extract_staff_records.
    
    Source: postgresql - 172.22.24.7:5432/postgres
    Target: tenant_novasight_demo.stg_staff_records
    Primary Keys: id, branch, staff_id
    CDC Column: created_at (timestamp)
    
    SCD Type 2 columns added:
    - _scd_valid_from: Timestamp when record became valid
    - _scd_valid_to: Timestamp when record was superseded (null if current)
    - _scd_is_current: Boolean flag for current record
    - _scd_version: Version number for the record
    - _scd_hash: Hash of tracked columns for change detection
    """
    
    def __init__(self, spark: SparkSession):
        self.spark = spark
        self.app_name = "extract_staff_records"
        self.app_id = "3ef7910b-8e7b-411b-9fd5-6f12c421a4d2"
        
        # Source configuration
        self.source_config = {
            "db_type": "postgresql",
            "host": os.getenv("SOURCE_DB_HOST", "postgres"),
            "port": int(os.getenv("SOURCE_DB_PORT", "5432")),
            "database": "postgres",
            "schema": "public",
            "username": os.getenv("SOURCE_DB_USER", "novasight"),
            "password": os.getenv("SOURCE_DB_PASSWORD", "novasight"),
        }
        
        # Target configuration
        self.target_config = {
            "database": "tenant_novasight_demo",
            "table": "stg_staff_records",
            "engine": "MergeTree",
        }
        
        # SCD configuration
        self.primary_keys = [
            "id",
            "branch",
            "staff_id",
        ]
        
        # Tracked columns (all selected columns except PKs)
        self.tracked_columns = [
            "nid",
            "name",
            "department",
            "position",
            "nationality",
            "hire_date",
            "contract_start_date",
            "contract_end_date",
            "termination_reason",
            "notes",
            "termination_date",
            "entry_user",
            "created_at",
        ]
        
        # CDC configuration
        self.cdc_column = "created_at"
        self.cdc_type = "timestamp"
        
        # Job configuration
        self.batch_size = 10000
        self.current_timestamp = datetime.utcnow()
        
    def get_jdbc_url(self) -> str:
        """Build JDBC URL based on database type."""
        db_type = self.source_config["db_type"]
        host = self.source_config["host"]
        port = self.source_config["port"]
        database = self.source_config["database"]
        
        jdbc_drivers = {
            "postgresql": f"jdbc:postgresql://{host}:{port}/{database}",
            "mysql": f"jdbc:mysql://{host}:{port}/{database}",
            "oracle": f"jdbc:oracle:thin:@{host}:{port}:{database}",
            "sqlserver": f"jdbc:sqlserver://{host}:{port};databaseName={database}",
        }
        
        return jdbc_drivers.get(db_type, f"jdbc:postgresql://{host}:{port}/{database}")
    
    def get_jdbc_driver(self) -> str:
        """Get JDBC driver class name."""
        drivers = {
            "postgresql": "org.postgresql.Driver",
            "mysql": "com.mysql.cj.jdbc.Driver",
            "oracle": "oracle.jdbc.OracleDriver",
            "sqlserver": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        }
        return drivers.get(self.source_config["db_type"], "org.postgresql.Driver")
    
    def get_high_watermark(self) -> str:
        """Get high watermark from state store for CDC."""
        watermark_file = f"/tmp/watermark_{self.app_id}.txt"
        try:
            with open(watermark_file, 'r') as f:
                return f.read().strip()
        except FileNotFoundError:
            return None
    
    def save_high_watermark(self, value: str):
        """Save high watermark to state store."""
        watermark_file = f"/tmp/watermark_{self.app_id}.txt"
        with open(watermark_file, 'w') as f:
            f.write(str(value))
        logger.info(f"Saved high watermark: {value}")
    
    def compute_hash(self, df: DataFrame) -> DataFrame:
        """Compute hash of tracked columns for change detection."""
        hash_cols = [col(c).cast("string") for c in self.tracked_columns]
        return df.withColumn(
            "_scd_hash",
            md5(concat_ws("||", *hash_cols))
        )
    
    def read_source(self) -> DataFrame:
        """Read data from source database with optional CDC filtering."""
        logger.info(f"Reading from source: {self.source_config['database']}")
        
        jdbc_url = self.get_jdbc_url()
        jdbc_driver = self.get_jdbc_driver()
        
        connection_props = {
            "user": self.source_config["username"],
            "password": self.source_config["password"],
            "driver": jdbc_driver,
            "fetchsize": str(self.batch_size),
        }
        
        table_name = "public.staff_records"
        base_query = f"SELECT * FROM {table_name}"
        
        high_watermark = self.get_high_watermark()
        if high_watermark:
            query = f"SELECT * FROM ({base_query}) sq WHERE created_at > '{high_watermark}'"
            logger.info(f"CDC filter applied: created_at > {high_watermark}")
        else:
            query = base_query
        
        df = self.spark.read.jdbc(
            url=jdbc_url,
            table=f"({query}) AS source_data",
            properties=connection_props
        )
        
        # Select configured columns
        selected_columns = [
            "id",
            "branch",
            "staff_id",
            "nid",
            "name",
            "department",
            "position",
            "nationality",
            "hire_date",
            "contract_start_date",
            "contract_end_date",
            "termination_reason",
            "notes",
            "termination_date",
            "entry_user",
            "created_at",
        ]
        
        df = df.select([col(c) for c in selected_columns])
        
        # Compute hash for change detection
        df = self.compute_hash(df)
        
        row_count = df.count()
        logger.info(f"Read {row_count} rows from source")
        return df
    
    def get_clickhouse_connection(self) -> tuple:
        """Get ClickHouse connection details."""
        target_url = os.getenv("CLICKHOUSE_URL", "jdbc:clickhouse://clickhouse:8123")
        target_host = os.getenv("CLICKHOUSE_HOST", "clickhouse")
        target_port = os.getenv("CLICKHOUSE_PORT", "8123")
        target_user = os.getenv("CLICKHOUSE_USER", "default")
        target_password = os.getenv("CLICKHOUSE_PASSWORD", "")
        return target_url, target_host, target_port, target_user, target_password
    
    def ensure_target_table_exists(self):
        """Create target table in ClickHouse if it doesn't exist."""
        _, target_host, target_port, target_user, target_password = self.get_clickhouse_connection()
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        # Build column definitions based on source columns
        column_defs = [
            "id Int32",
            "branch String",
            "staff_id String",
            "nid Nullable(String)",
            "name Nullable(String)",
            "department Nullable(String)",
            "position Nullable(String)",
            "nationality Nullable(String)",
            "hire_date Nullable(Date)",
            "contract_start_date Nullable(Date)",
            "contract_end_date Nullable(Date)",
            "termination_reason Nullable(String)",
            "notes Nullable(String)",
            "termination_date Nullable(Date)",
            "entry_user Nullable(String)",
            "created_at Nullable(DateTime64(6))",
            # SCD Type 2 columns
            "_scd_hash String",
            "_scd_valid_from DateTime64(6) DEFAULT now64()",
            "_scd_valid_to Nullable(DateTime64(6))",
            "_scd_is_current Bool DEFAULT true",
            "_scd_version UInt32 DEFAULT 1",
            "_novasight_app_id String",
            "_novasight_tenant_id String",
            "_novasight_loaded_at DateTime64(6) DEFAULT now64()"
        ]
        
        columns_sql = ",\\n    ".join(column_defs)
        
        # Build ORDER BY from primary keys + _scd_valid_from
        order_by_cols = ", ".join(self.primary_keys + ["_scd_valid_from"])
        primary_key_cols = ", ".join(self.primary_keys)
        
        create_sql = f"""
        CREATE TABLE IF NOT EXISTS {target_table} (
            {columns_sql}
        ) ENGINE = MergeTree()
        ORDER BY ({order_by_cols})
        PRIMARY KEY ({primary_key_cols})
        """
        
        logger.info(f"Ensuring target table exists: {target_table}")
        
        try:
            # Use ClickHouse HTTP interface to execute DDL
            params = {"query": create_sql}
            if target_user:
                params["user"] = target_user
            if target_password:
                params["password"] = target_password
            
            query_string = urllib.parse.urlencode(params)
            http_url = f"http://{target_host}:{target_port}/?{query_string}"
            
            req = urllib.request.Request(http_url, method='POST')
            with urllib.request.urlopen(req, timeout=30) as response:
                if response.status == 200:
                    logger.info(f"Table {target_table} is ready")
                else:
                    logger.warning(f"Table creation response: {response.read().decode()}")
        except Exception as e:
            logger.warning(f"Could not create table via HTTP, will try JDBC: {e}")
    
    def read_target_current(self) -> DataFrame:
        """Read current records from target."""
        target_url, _, _, target_user, target_password = self.get_clickhouse_connection()
        
        connection_props = {
            "user": target_user,
            "password": target_password,
            "driver": "com.clickhouse.jdbc.ClickHouseDriver",
        }
        
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        try:
            # Read only current records
            query = f"SELECT * FROM {target_table} WHERE _scd_is_current = true"
            
            return self.spark.read.jdbc(
                url=target_url,
                table=f"({query}) AS target_current",
                properties=connection_props
            )
        except Exception as e:
            logger.warning(f"Could not read target table: {e}")
            return None
    
    def identify_changes(self, source_df: DataFrame, target_df: DataFrame) -> tuple:
        """
        Identify new, updated, and unchanged records.
        
        Returns:
            Tuple of (inserts_df, updates_df, unchanged_count)
        """
        if target_df is None or target_df.isEmpty():
            # All records are new
            return source_df, self.spark.createDataFrame([], source_df.schema), 0
        
        # Alias for clarity
        source = source_df.alias("src")
        target = target_df.alias("tgt")
        
        # Join on primary keys
        join_condition = [source[pk] == target[pk] for pk in self.primary_keys]
        
        joined = source.join(target, on=join_condition, how="left")
        
        # New records: no match in target
        new_records = joined.filter(
            target[self.primary_keys[0]].isNull()
        ).select([source[c] for c in source_df.columns])
        
        # Existing records: match in target
        existing = joined.filter(
            target[self.primary_keys[0]].isNotNull()
        )
        
        # Changed records: hash is different
        changed_records = existing.filter(
            source["_scd_hash"] != target["_scd_hash"]
        ).select([source[c] for c in source_df.columns])
        
        # Unchanged count
        unchanged_count = existing.filter(
            source["_scd_hash"] == target["_scd_hash"]
        ).count()
        
        logger.info(
            f"Identified {new_records.count()} new, "
            f"{changed_records.count()} changed, "
            f"{unchanged_count} unchanged records"
        )
        
        return new_records, changed_records, unchanged_count
    
    def prepare_new_records(self, df: DataFrame) -> DataFrame:
        """Prepare new records with SCD Type 2 columns."""
        return df \
            .withColumn("_scd_valid_from", lit(self.current_timestamp)) \
            .withColumn("_scd_valid_to", lit(None).cast("timestamp")) \
            .withColumn("_scd_is_current", lit(True)) \
            .withColumn("_scd_version", lit(1)) \
            .withColumn("_novasight_app_id", lit(self.app_id)) \
            .withColumn("_novasight_tenant_id", lit("9b2ab68a-f819-41fa-bf51-916440c34cbd")) \
            .withColumn("_novasight_loaded_at", current_timestamp())
    
    def prepare_updated_records(self, df: DataFrame, target_df: DataFrame) -> tuple:
        """
        Prepare updates: close old records and create new versions.
        
        Returns:
            Tuple of (expired_records_df, new_version_records_df)
        """
        # Get current versions to expire
        pk_condition = [df[pk] == target_df[pk] for pk in self.primary_keys]
        
        matched = target_df.join(
            df.select(self.primary_keys),
            on=self.primary_keys,
            how="inner"
        )
        
        # Expire old records
        expired = matched \
            .withColumn("_scd_valid_to", lit(self.current_timestamp)) \
            .withColumn("_scd_is_current", lit(False))
        
        # Get max version for each PK
        version_window = Window.partitionBy(self.primary_keys)
        max_versions = target_df \
            .select(self.primary_keys + ["_scd_version"]) \
            .withColumn("_max_version", spark_max("_scd_version").over(version_window)) \
            .select(self.primary_keys + ["_max_version"]) \
            .dropDuplicates()
        
        # Create new versions
        new_versions = df.join(max_versions, on=self.primary_keys, how="left")
        new_versions = new_versions \
            .withColumn("_scd_valid_from", lit(self.current_timestamp)) \
            .withColumn("_scd_valid_to", lit(None).cast("timestamp")) \
            .withColumn("_scd_is_current", lit(True)) \
            .withColumn("_scd_version", coalesce(col("_max_version"), lit(0)) + 1) \
            .drop("_max_version") \
            .withColumn("_novasight_app_id", lit(self.app_id)) \
            .withColumn("_novasight_tenant_id", lit("9b2ab68a-f819-41fa-bf51-916440c34cbd")) \
            .withColumn("_novasight_loaded_at", current_timestamp())
        
        return expired, new_versions
    
    
    def write_to_target(self, df: DataFrame, mode: str = "append"):
        """Write data to ClickHouse target."""
        if df.isEmpty():
            return 0
            
        target_url, _, _, target_user, target_password = self.get_clickhouse_connection()
        
        connection_props = {
            "user": target_user,
            "password": target_password,
            "driver": "com.clickhouse.jdbc.ClickHouseDriver",
        }
        
        target_table = f"{self.target_config['database']}.{self.target_config['table']}"
        
        
        df.write.jdbc(
            url=target_url,
            table=target_table,
            mode=mode,
            properties=connection_props
        )
        
        return df.count()
    
    def run(self):
        """Execute the SCD Type 2 job."""
        logger.info(f"Starting SCD Type 2 job: {self.app_name}")
        start_time = datetime.now()
        
        try:
            # Ensure target table exists in ClickHouse
            self.ensure_target_table_exists()
            
            # Read source data
            source_df = self.read_source()
            
            if source_df.isEmpty():
                logger.info("No new data to process")
                return {
                    "status": "success",
                    "rows_processed": 0,
                    "rows_inserted": 0,
                    "rows_updated": 0,
                    "rows_expired": 0,
                    "duration_seconds": 0,
                }
            
            # Read current records from target
            target_df = self.read_target_current()
            
            # Identify changes
            new_records, changed_records, unchanged_count = self.identify_changes(
                source_df, target_df
            )
            
            # Process new records
            new_with_scd = self.prepare_new_records(new_records)
            new_count = self.write_to_target(new_with_scd)
            
            # Process updates (expire old, insert new version)
            expired_count = 0
            updated_count = 0
            
            if not changed_records.isEmpty() and target_df is not None:
                expired_records, new_versions = self.prepare_updated_records(
                    changed_records, target_df
                )
                
                # Write expired records (update in place - ClickHouse specific)
                # Note: In ClickHouse, we'd use ALTER TABLE UPDATE or CollapsingMergeTree
                expired_count = expired_records.count()
                
                # Write new versions
                updated_count = self.write_to_target(new_versions)
            
            # Update high watermark
            max_watermark = source_df.agg({self.cdc_column: "max"}).collect()[0][0]
            if max_watermark:
                self.save_high_watermark(str(max_watermark))
            
            duration = (datetime.now() - start_time).total_seconds()
            logger.info(f"SCD Type 2 job completed in {duration:.2f} seconds")
            
            return {
                "status": "success",
                "rows_processed": source_df.count(),
                "rows_inserted": new_count,
                "rows_updated": updated_count,
                "rows_expired": expired_count,
                "rows_unchanged": unchanged_count,
                "duration_seconds": duration,
            }
            
        except Exception as e:
            logger.error(f"SCD Type 2 job failed: {str(e)}")
            raise


def main():
    """Main entry point."""
    spark = SparkSession.builder \
        .appName("extract_staff_records") \
        .config("spark.sql.adaptive.enabled", "true") \
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true") \
        .config("spark.sql.shuffle.partitions", "200") \
        .getOrCreate()
    
    try:
        job = SCDType2Job(spark)
        result = job.run()
        logger.info(f"Job result: {result}")
    finally:
        spark.stop()


if __name__ == "__main__":
    main()

