"""add_saved_queries_table

Revision ID: b5400357036d
Revises: 53a2e62b06e9
Create Date: 2026-02-11 11:33:36.459761
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5400357036d'
down_revision: Union[str, None] = '53a2e62b06e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('query_type', sa.Enum('ADHOC', 'PYSPARK', 'DBT', 'REPORT', name='querytype'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('is_clickhouse', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_savedquery_name')
    )
    op.create_index(op.f('ix_saved_queries_tenant_id'), 'saved_queries', ['tenant_id'], unique=False)
    op.drop_index('idx_platform_audit_created', table_name='platform_audit_log')
    op.drop_table('platform_audit_log')
    op.drop_table('platform_admins')
    op.drop_table('_metadata', schema='tenant_test_hospital4')
    op.drop_table('_metadata', schema='tenant_hnh')
    op.drop_table('alembic_version')
    op.drop_table('_metadata', schema='tenant_givc')
    op.drop_constraint('dag_configs_tenant_id_fkey', 'dag_configs', type_='foreignkey')
    op.create_foreign_key(None, 'dag_configs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('data_connections_tenant_id_fkey', 'data_connections', type_='foreignkey')
    op.create_foreign_key(None, 'data_connections', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_connections', type_='foreignkey')
    op.create_foreign_key('data_connections_tenant_id_fkey', 'data_connections', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(None, 'dag_configs', type_='foreignkey')
    op.create_foreign_key('dag_configs_tenant_id_fkey', 'dag_configs', 'tenants', ['tenant_id'], ['id'])
    op.create_table('_metadata',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='_metadata_pkey'),
    schema='tenant_givc'
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('_metadata',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='_metadata_pkey'),
    schema='tenant_hnh'
    )
    op.create_table('_metadata',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='_metadata_pkey'),
    schema='tenant_test_hospital4'
    )
    op.create_table('platform_admins',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='platform_admins_pkey'),
    sa.UniqueConstraint('email', name='platform_admins_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('platform_audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['platform_admins.id'], name='platform_audit_log_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='platform_audit_log_pkey')
    )
    op.create_index('idx_platform_audit_created', 'platform_audit_log', [sa.text('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_saved_queries_tenant_id'), table_name='saved_queries')
    op.drop_table('saved_queries')
    # ### end Alembic commands ###
